# Generated by Django 4.0.2 on 2023-04-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='account_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
